### PR TITLE
Support Python 2.7+

### PR DESCRIPTION
**Pull request by jwiggins**
Tested on Python 2.7 and 3.5; seems to work.

### CODE REVIEW

**Comment by jwiggins** [comment]
Lordy. I'm now the Nth Python 3 port...

**Comment by rkern** [comment]
I'm still settling in after my move back to the US, so I'm a bit distracted. @matthew-brett @jvkersch @jwiggins @rgommers Any votes for one PR over the others? A grand merging to one PR?

**Comment by jwiggins** [comment]
You're back in the US? Picked an interesting time... 😉 

Right. So, @jvkersch's and @matthew-brett's versions are a lot more complete than mine. I would vote for a combo of those. However, I think using `struct` to build the bytestrings in a version-agnostic way is kinda nifty, so I would use that from my branch.

**Comment by matthew-brett** [comment]
I think the question is how grin should deal with encoding in text files.
I guess y'all want to replicate the behavior of grep?   My version doesn't
try to decode text, in that it assumes latin1, an alternative is to assume
utf-8 or something else, and deal gracefully with any decoding errors.​

**Comment by rgommers** [comment]
> I guess y'all want to replicate the behavior of grep? 

Not sure what that does (I use `grin` always:)). I'd prefer the Python 2 behavior, guessing (almost always) right beats being pedantic.

**Comment by matthew-brett** [comment]
I seem to remember that 'grin' is using str, therefore not attempting to decode - that's why I went for the no-decoding option with 'latin1'.

**Comment by partounian** [comment]
Just to note for anyone interested in python3 support now there is grin3.
https://pypi.python.org/pypi/grin3/1.2.3

**Pull request closed without merging**
